const {JSDOM}=require(process.env.JSDOM_MODULE||'jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test/manuales/',runScripts:'outside-only'});
const w=dom.window;w.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('manuales.json','utf8'))});
w.eval(fs.readFileSync('app.js','utf8')+'\nwindow.app=AppUI;window.data=DataService;window.storage=StorageService;');
(async()=>{
 w.app.cacheDOM();w.app.bindEvents();w.app.populateFilters();
 let release;const originalFetch=w.fetch;w.fetch=async()=>{await new Promise(resolve=>release=resolve);return originalFetch();};
 const loading=w.app.initializeApp();w.document.querySelector('.cat-btn[data-cat="Alarmas"]').click();release();await loading;
 assert.equal(w.document.getElementById('filter-category').value,'Alarmas');assert(w.document.querySelectorAll('#search-results .item-card').length>0);
 w.app.navigate('view-ficha');
 const el=id=>w.document.getElementById(id),fill=(id,value)=>el(id).value=value;
 fill('f-cliente','Cliente');fill('f-ch-1-ip','10.1.1.2');fill('f-ch-1-modelo','Modelo libre');fill('f-z-1-tipo','Retardada');fill('f-z-1-particion','2');
 w.app.navigate('view-home');w.app.navigate('view-ficha');w.app.navigate('view-ficha');assert.equal(el('f-cliente').value,'Cliente');
 el('btn-add-camera').click();el('btn-add-zone').click();assert.equal(el('f-ch-1-ip').value,'10.1.1.2');assert.equal(el('f-z-1-tipo').value,'Retardada');
 const fields={marca:'Marca libre',serie:'SN123',mac:'aa:bb:cc',puerto:'554',usuario:'operador',tipo:'Domo',resolucion:'8 MP',alimentacion:'PoE',observaciones:'Prueba'};
 for(const [key,value] of Object.entries(fields))fill('f-ch-1-'+key,value);
 for(const [id,value] of Object.entries({'f-grab-modelo':'Grabador libre','f-grab-serie':'GR123','f-grab-mac':'dd:ee:ff','f-grab-puertos':'HTTPS','f-alarm-serie':'AL123','f-z-1-numero':'7','f-z-1-modelo':'Sensor libre','f-z-1-observaciones':'Zona prueba'}))fill(id,value);
 w.document.querySelector('[data-target="dns-input"]').click();fill('dns-input','dominio.test');
 let txt=w.app.generarTextoFicha();for(const value of [...Object.values(fields),'10.1.1.2','Modelo libre','Retardada','Partición: 2','GR123','AL123','Sensor libre','DDNS'])assert(txt.includes(value),value);
 assert(!/N\/A|Dahua|Ajax|Cámara 2|Zona 2|Sin seleccionar/.test(txt));w.app.updateZoneCount();assert.equal(el('zone-count').textContent,'1 zonas cumplimentadas');
 w.document.querySelector('[data-target="dns-input"]').click();assert(!w.app.generarTextoFicha().includes('dominio.test'));
 for(const category of ['Control de Acceso','Electricidad','Otros']) {fill('filter-brand','Dahua');w.document.querySelector(`.cat-btn[data-cat="${category}"]`).click();assert.equal(el('filter-brand').value,'');assert.equal(el('search-results').querySelectorAll('.item-card').length,0);assert(el('search-results').textContent.includes('todavía no tiene equipos'));}
 w.data.manuals.push({id:'test',categoria:'Nueva categoría'});w.app.populateFilters();assert(w.document.querySelector('.cat-btn[data-cat="Nueva categoría"]'));
 el('header-action').click();assert(el('view-more').classList.contains('active'));
 fill('filter-category','');fill('secondary-search','nvr');w.app.renderSearch();assert(el('search-results').querySelectorAll('.item-card').length>0);
 let opened;w.app.openDetail=id=>opened=id;el('search-results').querySelector('.item-card').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter'}));assert(opened);
 w.storage.toggleFavorite(opened);w.storage.addToHistory(opened);w.storage.setTheme('dark');assert(w.storage.isFavorite(opened));assert.equal(w.storage.getHistory()[0],opened);
 assert.deepEqual(Object.keys(w.localStorage).sort(),['biblioteca_favoritos','biblioteca_historial','biblioteca_tema']);
 for(const field of w.document.querySelectorAll('#ficha-form-container input:not([type=checkbox]),#ficha-form-container select,#ficha-form-container textarea'))assert(w.document.querySelector(`label[for="${field.id}"]`),field.id);
 const pdfs=new Map();w.caches={open:async()=>({match:async url=>pdfs.get(url),put:async(url,response)=>pdfs.set(url,response),delete:async url=>pdfs.delete(url)}),delete:async()=>{pdfs.clear();return true;}};
 w.fetch=async()=>new Response('pdf',{headers:{'content-type':'application/pdf'}});
 assert.equal(await w.app.toggleOffline('./manual.pdf'),true);assert.equal(await w.app.isCached('./manual.pdf'),true);
 assert.equal(await w.app.toggleOffline('./manual.pdf'),false);assert.equal(await w.app.isCached('./manual.pdf'),false);
 await w.app.toggleOffline('./manual.pdf');await w.app.clearPdfCache();assert.equal(await w.app.isCached('./manual.pdf'),false);
 w.caches.open=async()=>{throw new Error('Cache disabled');};assert.equal(await w.app.isCached('./manual.pdf'),false);
 let copied;w.alert=()=>{};Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>copied=text}});
 await el('btn-copy-ficha').onclick();assert(copied.includes('SN123'));
 let downloaded;w.URL.createObjectURL=blob=>{downloaded=blob;return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){assert.equal(this.download,'Ficha_Instalacion.txt');};
 el('btn-download-ficha').click();assert(downloaded instanceof w.Blob);assert(downloaded.size>0);
 console.log('PASS: memory-only persistence, append, technical TXT, no defaults, DDNS, zone count, categories, search, keyboard, favorites/history/theme, labels');w.close();
})().catch(error=>{console.error(error);process.exit(1)});
